# .cpanel.yml

---
deployment:
  tasks:
    - export DEPLOYPATH=/home/your-username/public_html/
    - export LARAVELPATH=/home/your-username/laravel-app/

    # Clone atau update kode ke folder Laravel (di luar public_html)
    - /bin/mkdir -p $LARAVELPATH
    - /bin/cp -R * $LARAVELPATH

    # Install dependencies dengan Composer
    - cd $LARAVELPATH && /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader

    # Set file permissions
    - /bin/chmod -R 775 $LARAVELPATH/storage $LARAVELPATH/bootstrap/cache

    # Copy file public ke public_html
    - /bin/cp -R $LARAVELPATH/public/* $DEPLOYPATH

    # Update index.php di public_html agar sesuai dengan path Laravel
    - echo "<?php
      require __DIR__.'/../laravel-app/vendor/autoload.php';
      \$app = require_once __DIR__.'/../laravel-app/bootstrap/app.php';
      \$kernel = \$app->make(Illuminate\Contracts\Http\Kernel::class);
      \$response = \$kernel->handle(\$request = Illuminate\Http\Request::capture());
      \$response->send();
      \$kernel->terminate(\$request, \$response);" > $DEPLOYPATH/index.php
