deployment:
  tasks:
    - export DEPLOYPATH=/home/<cpanel_user>/public_html
    - /bin/cp -R $GIT_WORK_TREE/* $DEPLOYPATH
    - /bin/cp -R $GIT_WORK_TREE/.env $DEPLOYPATH
    - cd $DEPLOYPATH && /usr/local/bin/php artisan optimize
    - cd $DEPLOYPATH && /usr/local/bin/php artisan migrate --force
